import { Inter } from "next/font/google";
import "./globals.css";
import Siderbar from "@/components/Siderbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex items-start h-screen overflow-hidden`}>
        <Siderbar />
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
